cc_library(name = 'leveldb',
           deps = ['//thirdparty/leveldb-1.9.0/:leveldb'],
           )

cc_library(name = 'util',
           deps = ['//thirdparty/leveldb-1.9.0/util:util'],
           )

cc_library(name = 'skiplist',
           deps = ['//thirdparty/leveldb-1.9.0/db:skiplist'],
           )

cc_library(name = 'cache',
           deps = ['//thirdparty/leveldb-1.9.0/util:cache'],
           )

cc_library(name = 'hash',
           deps = ['//thirdparty/leveldb-1.9.0/util:hash'],
           )

cc_library(name = 'arena',
           deps = ['//thirdparty/leveldb-1.9.0/util:arena'],
           )

cc_library(name = 'env',
           deps = ['//thirdparty/leveldb-1.9.0/util:env'],
           )

cc_library(name = 'coding',
           deps = ['//thirdparty/leveldb-1.9.0/util:coding'],
           )

cc_library(name = 'crc32c',
           deps = ['//thirdparty/leveldb-1.9.0/util:crc32c'],
           )
