cc_library(
    name = 'util',
    srcs = [
        'arena.cc',
        'hash.cc',
        'pcre.cc',
        'random.cc',
        'rune.cc',
        'stringpiece.cc',
        'stringprintf.cc',
        'strutil.cc',
        'test.cc',
        'thread.cc',
        'valgrind.cc'
    ],
    deps = ['//thirdparty/gflags:gflags',
            '//thirdparty/glog:glog',
            ],
    warning = 'no'
)

#cc_library(name = 'benchmark',
#           srcs = ['benchmark.cc',],
#           )