cc_library(
    name = 'gtest',
    deps = ['//thirdparty/googletest-1.8.1/googletest/:gtest']
)

cc_library(
    name = 'gtest_main',
    deps = ['//thirdparty/googletest-1.8.1/googletest/:gtest_main']
)

cc_test(
    name = 'gtest_test',
    srcs = 'gtest_test.cpp'
)
