cc_library(
    name = 'gtest',
    deps = ['//thirdparty/gtest-1.6.0/:gtest']
)

cc_library(
    name = 'gtest_main',
    deps = ['//thirdparty/gtest-1.6.0/:gtest_main']
)

cc_test(
    name = 'gtest_test',
    srcs = 'gtest_test.cpp'
)
