
// Generated by HeaderExtractor.
// Copyright 2013 Huahang Liu.
// All rights reserved.

#pragma once

#include "thirdparty/boost_1_54_0/boost/geometry/multi/algorithms/detail/overlay/self_turn_points.hpp"
