
// Generated by HeaderExtractor.
// Copyright 2013 Huahang Liu.
// All rights reserved.

#pragma once

#include "thirdparty/boost_1_54_0/boost/fusion/view/iterator_range/detail/is_segmented_impl.hpp"
