
// Generated by HeaderExtractor.
// Copyright 2013 Huahang Liu.
// All rights reserved.

#pragma once

#include "thirdparty/boost_1_54_0/boost/geometry/strategies/spherical/distance_cross_track.hpp"
