cc_library(
    name = 'ev',
    srcs = 'ev.cpp',
    extra_cppflags = [
        '-Wno-sign-compare',
        '-Wno-strict-aliasing',
        '-Wno-float-equal',
        '-Wno-unused-result',
    ],
)
