
// Generated by HeaderExtractor.
// Copyright 2013 Huahang Liu.
// All rights reserved.

#pragma once

#include "thirdparty/boost_1_54_0/boost/intrusive/detail/has_member_function_callable_with.hpp"
