
// Generated by HeaderExtractor.
// Copyright 2013 Huahang Liu.
// All rights reserved.

#pragma once

#include "thirdparty/boost_1_54_0/boost/test/utils/runtime/cla/detail/argument_value_usage.hpp"
